// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketClassLibrary.Models;

#nullable disable

namespace TicketClassLibrary.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    partial class TicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketClassLibrary.Models.Employee", b =>
                {
                    b.Property<string>("EmpId")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("EmpId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TicketTypeId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.HasKey("TicketId");

                    b.HasIndex("EmpId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.TicketAssignment", b =>
                {
                    b.Property<string>("AssignmentId")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Support_Emp_Id")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("Support_Emp_Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketAssignment");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.TicketComment", b =>
                {
                    b.Property<string>("CommentId")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("Support_Emp_Id")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)")
                        .HasColumnName("Support_Emp_Id");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.HasKey("CommentId");

                    b.HasIndex("EmpId");

                    b.HasIndex("Support_Emp_Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComment");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.TicketPriority", b =>
                {
                    b.Property<string>("PriorityId")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("PriorityDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ResolutionTime")
                        .HasColumnType("int");

                    b.Property<int>("ResponseTime")
                        .HasColumnType("int");

                    b.HasKey("PriorityId");

                    b.ToTable("TicketPriority");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.TicketType", b =>
                {
                    b.Property<string>("TicketTypeId")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PriorityId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TicketTypeId");

                    b.HasIndex("PriorityId");

                    b.ToTable("TicketType");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.Ticket", b =>
                {
                    b.HasOne("TicketClassLibrary.Models.Employee", "Employee")
                        .WithMany("Tickets")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketClassLibrary.Models.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.TicketAssignment", b =>
                {
                    b.HasOne("TicketClassLibrary.Models.Employee", "Employee")
                        .WithMany("TicketAssignments")
                        .HasForeignKey("Support_Emp_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketClassLibrary.Models.Ticket", "Ticket")
                        .WithMany("TicketAssignments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.TicketComment", b =>
                {
                    b.HasOne("TicketClassLibrary.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketClassLibrary.Models.Employee", "SupportEmployee")
                        .WithMany()
                        .HasForeignKey("Support_Emp_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TicketClassLibrary.Models.Ticket", "Ticket")
                        .WithMany("TicketComments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("SupportEmployee");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.TicketType", b =>
                {
                    b.HasOne("TicketClassLibrary.Models.TicketPriority", "TicketPriority")
                        .WithMany("TicketTypes")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TicketPriority");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.Employee", b =>
                {
                    b.Navigation("TicketAssignments");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.Ticket", b =>
                {
                    b.Navigation("TicketAssignments");

                    b.Navigation("TicketComments");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.TicketPriority", b =>
                {
                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("TicketClassLibrary.Models.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
