// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserLibrary.Models;

#nullable disable

namespace UserLibrary.Migrations
{
    [DbContext(typeof(UserDBContext))]
    [Migration("20260120114755_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserLibrary.Models.LoginUser", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.HasKey("Username");

                    b.ToTable("LoginUser");
                });
#pragma warning restore 612, 618
        }
    }
}
